server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:*"
            allowedMethods: ["GET", "POST", "PUT", "OPTIONS"]
            allowedHeaders: "*"
      routes:
        - id: monitored-api
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
        - id: dashboard-service
          uri: http://localhost:8083
          predicates:
            - Path=/dashboard/**
          filters:
            - RewritePath=/dashboard/(?<segment>.*), /api/v1/dashboard/${segment}
        - id: alert-service
          uri: http://localhost:8082
          predicates:
            - Path=/alerts,/alerts/**
          filters:
            - RewritePath=/alerts(?<segment>/?.*), /api/v1/alerts${segment}
        - id: orange-api
          uri: http://localhost:8091
          predicates:
            - Path=/api/**