server:
  port: 8090

spring:
  application:
    name: travel-agency-api

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

monitoring:
  service-name: travel-agency-api
  enabled: true